### ISSUE TITLE
"Unable to Retrieve Note" error

### ISSUE THREAD

**Issue by tonybranfort** [tonybranfort/immidb#41]
User reported getting error `Database error. Unable to retrieve note. Error has been recorded for follow-up.` 

User 5883c62b16dc9fcb644eeed7 reported 7/26/17 10:28 AM CT on client 58bd91d90768a011bc7d1e24. 

These were the steps user reported that led to the error: 
1. Click new note button. 
2. Fill in note.
3. Select 6 people to receive note via email in Notify dropdown. 
4. Click Save & Send.
5. **Got error shown above.**
6. New note was not listed in note list on client. 
7. User recreated note with send to users.  Note saved and sent successfully.

**Comment by tonybranfort** [comment]
Log and error below.  All users in system received the error because of the publish/subscribe when a new note is created.  
```
{
  "_id": "5978b36b254a711443da703b",
  "msg": "ERROR (public,api). note/index.js + getNote(): No Note found",
  "level": "error",
  "error": {
    "message": "note/index.js + getNote(): No Note found",
    "userMessage": "Database error.  Unable to retrieve note.",
    "stack": (below)
  },
  "createdTS": "2017-07-26T15:21:15.326Z",
  "expires": "2018-01-22T15:21:15.326Z",
  "__v": 0,
  "req": {
    "ip": "63.225.154.15",
    "method": "GET",
    "originalUrl": "/api/note/5978b36b254a711443da7034",
    "path": "/note/5978b36b254a711443da7034",
    "userId": "xxxx",
    "req_id": "980d306019e55b78f34d008d54bd241d42351a40"
  }
}
````

**Error stack**
```Error: note/index.js + getNote(): No Note found
    at /home/ec2-user/knn/app/modules/note/index.js:37:27
    at Query.<anonymous> (/home/ec2-user/knn/node_modules/mongoose/lib/model.js:3419:16)
    at /home/ec2-user/knn/node_modules/mongoose/node_modules/kareem/index.js:264:21
    at /home/ec2-user/knn/node_modules/mongoose/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by tonybranfort** [comment]
Same error occurred at 7/26/17 10:59:16 CT.  
```
{
  "_id": "5978bc54254a711443da707b",
  "msg": "ERROR (public,api). note/index.js + getNote(): No Note found",
  "level": "error",
  "error": {
    "message": "note/index.js + getNote(): No Note found",
    "userMessage": "Database error.  Unable to retrieve note.",
    "stack": (see below
  },
  "createdTS": "2017-07-26T15:59:16.945Z",
  "expires": "2018-01-22T15:59:16.945Z",
  "__v": 0,
  "req": {
    "ip": "63.225.154.15",
    "method": "GET",
    "originalUrl": "/api/note/5978bc54254a711443da7076",
    "path": "/note/5978bc54254a711443da7076",
    "userId": "",
    "req_id": "1817dec07a0711f016a16e693676a6cb8f9462ee"
  }
}
```
**Error stack**
```
Error: note/index.js + getNote(): No Note found
    at app/modules/note/index.js:37:27
    at Query.<anonymous> (node_modules/mongoose/lib/model.js:3419:16)
    at node_modules/mongoose/node_modules/kareem/index.js:264:21
    at node_modules/mongoose/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by tonybranfort** [comment]
Confirmed no message exists in messages collection for note 5978b36b254a711443da7034.  

Confirmed no error in node log on 7/26 for any note other than the "No Note Found" error.  So, no error recorded if note could not be saved.  

Basic code flow when a user creates a new note and gets this error : 
1. front end submits POST request with change object
2. client-api submits save to client index which simply submits change object to change.index.js.
3. change.index adds necessary attributes including _id.  
4. change.index saves the updated request object and returns the change object to the front end. 
5. note.service receives the updated change object and publishes with NOTE_CHANGE + note._id. 
6. client list (on client page - so very user that has open a client in database) is subscribed to NOTE_CHANGE and submits GET request for note _id.  
7. Because note _id is not found, error is returned: all users on a client (note list) receives error note not found. 

Front end client submits change request for new note without an _id.  _id is created on note object in change.index.js.

**Comment by tonybranfort** [comment]
Error has occurred 11 times since Feb 13 : 
7/27/17 17:27:58 note id 597a229c254a711443da72fb 
7/27/17 15:56:48 note id 597a0d3f254a711443da7289
7/26/17 15:59:17 note id 5978bc54254a711443da7076
7/26/17 15:24:43 note id 5978b36b254a711443da7034
6/28/17 21:37:05 note id 5954217f1f67ee12ca636245
5/11/17 20:24:11 note id 5914c86869b919338249e50d
5/9/17 23:01:55 note id 59124a6369b919338249e0fe
4/20/17 17:32:32 note id 58f8f0af69b919338249c292
3/9/17 18:33:02 note id 58c19fdd0768a011bc7d2530
2/13/17 21:01:56 note id 58a21ec35f696e0b3a9dea2c
2/13/17 18:20:58  note id 58a1f9085f696e0b3a9de932

**Comment by tonybranfort** [comment]
Both users that generated the 4 notes (errors) on 7/26 and 7/27 reported slow internet connections.  Related?

**Comment by tonybranfort** [comment]
Id `597a7bfd0caa11522d070c76` doesn't exist in any collection that I can find other than messages.associated._id.

**Comment by tonybranfort** [comment]
What's most baffling is that the logs indicate that a Send Only was requested (no note POST and log signature matches a Send Only test) BUT somehow a note id is created (messages.associated._id) - an id like that is only created on the server side.  How is it being created?

For note _id `5978b36b254a711443da7034`, matched every POST note in log +/- 2 minutes to when that happened to actual note being created in notes collection - and none match.  So every POST in log created a note - which seems to confirm that no POST for note `5978b36b254a711443da7034` occurred.  So how did the id `5978b36b254a711443da7034` get created?

**Comment by tonybranfort** [comment]
Able to manually reproduce by forcing note modal controller to send note as message without saving note first.  The exact same behavior and end result occurs as error.  Note id is created in message.index on server side when message.associated._id does not exist.  That's how it's created.  While it's unclear *how* this being allowed to happen in the note controller, it can be prevented by throwing an error in server message.index if associated is included but doesn't include _id.  Then show error in modal and prevent from closing.

**Comment by tonybranfort** [comment]
Commit 51bdb91594abf.  Throw error if attempt to create message that has an associated ("save and send" note) but it doesn't have an _id.  Don't allow edit note modal to close if error thrown.
