### ISSUE TITLE
Parentheses on client search cause error

### ISSUE THREAD

**Issue by tonybranfort** [tonybranfort/immidb#98]
These client searches cause errors: 
* '(ramon'
* 'ramon)'

``` javascript
SyntaxError: Invalid regular expression: /[^♡]*(r[^♡]*/: Unterminated group
    at RegExp (native)
    at ...\app\modules\client\index.js:337:49
    at Array.forEach (native)
    at ...\app\modules\client\index.js:325:15
    at Query.<anonymous> (...\node_modules\mongoose\lib\model.js:3748:16)
    at ...\node_modules\kareem\index.js:277:21
    at ...\node_modules\kareem\index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by tonybranfort** [comment]
This only occurs on Fake data due to Search not being re-indexed (recreated) after generating new phones for v2.2.0.

**Comment by tonybranfort** [comment]
Commit 318fc1a8b7
